{
    "name": "Inno Sale Order Plan",
    "version": "15.1.1",
    "summary": "Sale order planning and routes fulfillment",
    "description": "Used to Plan sale orders and redirect sale order fulfillment based on route set on the order line.",
    "depends": ['sale_stock', 'product', 'mail', 'hr', 'innorug_manufacture'],
    "data": [
        'data/ir_sequenxe.xml',
        'security/ir.model.access.csv',
        "security/security.xml",
        'views/view_sale_order_planning.xml',
        'wizards/view_import_planning.xml',
        "wizards/dyeing_receive.xml",
        "wizards/view_res_config_settings.xml",
        "wizards/view_dyeing_wiz.xml",
        'wizards/report_wiz_view.xml',
        'wizards/update_sale_order_order.xml',
        'views/sale_order_route.xml',
        'reports/dyeing_plan_report.xml',
        'views/revised_planning_views.xml',
        'reports/size_area_report.xml',
        'reports/material_issue_dyeing.xml',
        'reports/dyeing_order_report.xml',
        'reports/dyeing_receive_report.xml',
        'reports/purchase_report.xml',
        'reports/dyeing_invoice_report.xml',
        'reports/sale_order_customize.xml',
        'reports/sale_inventory_status_report.xml',
        'reports/inno_carpet_sale_order_summary.xml',
        'views/view_dyeing_material_issue.xml',
        'views/view_dyeing_intend.xml',
        'reports/dyeing_order_status.xml',
        'views/dyeing_order.xml',
        "views/sale_order_views.xml",
        'views/inno_dyeing_receive.xml',
        'views/view_dyeing_partner_api.xml',
        'views/menu_items.xml',
    ],
    'application': True,
    "installable": True,
    'license': 'LGPL-3',
}
