{
    "name": "Inno Finishing",
    "version": "16.1.1",
    "summary": "Finish Weaved Products",
    "description": "Will help to manage the all the process required to finish the weaved products.",
    "depends": ['mrp', 'innorug_manufacture', 'inno_default_config', 'stock', ],
    "data": [
        "security/security.xml",
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        "data/ir_cron.xml",
        "data/data.xml",
        'views/view_finishing_job_work.xml',
        'views/view_mrp_workcenter.xml',
        'views/rug_stocks_views.xml',
        'views/view_carpet_transfer.xml',
        'wizard/views_res_config_settings.xml',
        'wizard/views_inno_barcode_scan.xml',
        'wizard/bom_wizard_views.xml',
        # "reports/custom_header_template.xml",
        "reports/material_issue.xml",
        "reports/jobwork_reissue.xml",
        'reports/materials_issue_summary.xml',
        "reports/gate_pass_reports.xml",
        "reports/report_operation_gpass.xml",
        "reports/tds_advice_report.xml",
        "reports/baazar_receiving_reports.xml",
        "reports/report_returns_jobwork.xml",
        "reports/report_receive_challan.xml",
        "reports/barcode_wise_order_summary.xml",
        "reports/work_order_wise_outstanding_reports.xml",
        "reports/order_balance_reports.xml",
        "reports/finishing_receive_report.xml",
        "reports/finishing_bill_report.xml",
        "reports/finishing_payment_advice_report.xml",
        "reports/finishing_baazar_reports.xml",
        "reports/barcode_stock_ageing_report.xml",
        "views/quality_control_views.xml",
        "views/finishing_barcode_views.xml",
        'views/finishing_bom_views.xml',
        'views/work_order_views.xml',
        'views/finishing_baazar_views.xml',
        'views/finishing_bazaar_line_views.xml',
        'views/production_views.xml',
        'views/finishing_size_rate_view.xml',
        'wizard/operation_wiazard_views.xml',
        "wizard/size_wize_update_rate.xml",
        "wizard/amend_return_wizard.xml",
        'wizard/update_parent_operation.xml',
        'wizard/return_views.xml',
        "wizard/reports_wiz_views.xml",
        'menu/finishing_menu.xml',
        'views/user_access_views.xml'],
    'application': True,
    "installable": True,
    'license': 'LGPL-3',
}
