{
    "name": "Inno Packaging",
    "version": "16.1.1",
    "summary": "Pack Finished Products.",
    "description": """
                    Pack finishing product to deliver.
                    """,
    "depends": ['sale_stock', 'innorug_manufacture',],
    "data": ['security/ir.model.access.csv',
             'data/paperformat.xml',
             'data/ir_sequence.xml',
             'views/stock_picking.xml',
             "views/inno_packaging_views.xml",
             'views/stock_quant_package.xml',
             'wizards/view_print_label.xml',
             'views/invoice_group_views.xml',
             'views/view_packaging_invoice.xml',
             'wizards/packaging_wizard_views.xml',
             'wizards/package_segmentation.xml',
             'wizards/report_wiz_view.xml',
             'reports/full_package_label.xml',
             'reports/custom_label.xml',
             'reports/hospitality_label.xml',
             'reports/export_invoice.xml',
             'reports/cargo_reports.xml',
             'reports/report_order_sheet.xml',
             'reports/packagin_list_report.xml',
             'reports/group_label_report.xml',
             'reports/packaging_current_position.xml',
             'reports/packaging_register_report.xml',
             'reports/packing_summary.xml',
             'reports/surya_qr_label.xml',
             'reports/upc_label.xml',
             'reports/sci_custom_label.xml',
             'reports/livabliss.xml',
             'reports/livabliss_upc.xml',
             'menu/menu.xml',],
    'application': True,
    "installable": True,
    'license': 'LGPL-3',
}
