{
    "name": "Inno Research & Development",
    "version": "16.1.1",
    "summary": "Design new Products",
    "description": """
                    Create sampla design,\nPlan the consumption,
                    \nCreate a sample,\nIntegrate with the mail product after customer Validation.
                    """,
    "depends": ['product','mrp','innorug_manufacture','purchase',],
    "data": ["security/security.xml",
             'security/ir.model.access.csv',
             'data/ir_sequence.xml',
             "views/inno_product_supplierinfo.xml",
             "views/research_views.xml",
             "views/size_line_views.xml",
             "views/inno_production_views.xml",
             "views/rnd_operation_sequence_views.xml",
             "views/inno_size_views.xml",
             "views/master_data_views.xml",
             "views/bom_views.xml",
             "views/view_product_rate_group.xml",
             "wizards/order_wizards_views.xml",
             "wizards/add_consumption.xml",
             "wizards/design_copy_views.xml",
             "wizards/size_line_views.xml",
             "wizards/add_percent_bom_views.xml",
             'wizards/view_inno_product_sku.xml',
             "menu/inno_r_d_menu.xml",
    ],
    'application': True,
    "installable": True,
    'license': 'LGPL-3',
}
